config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'cart', to: 'cart#show'
  post 'cart/add'
  post 'cart/remove'
  resources :products
  resources :cards
  resources :items
  resources :line_items do
    member do
      post :add_to_cart
    end
  end
  resources :cours
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/card.rb
class Card < ApplicationRecord
    has_many :items
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :orderables

    has_many :products , through: :orderables #through: :join_association, source: :join_association_table_foreign_key_to_carts_table

    def total
      orderables.to_a.sum { |orderable| orderable.total}
    end
end

app/models/cour.rb
class Cour < ApplicationRecord
    #belongs_to :object, class_name: "object", foreign_key: "object_id"
    has_rich_text :content
    
    has_one_attached :thumbnail
    has_one_attached :video
end

app/models/item.rb
class Item < ApplicationRecord
    has_many :line_items

    belongs_to :card, class_name: "card", foreign_key: "card_id"
end

app/models/line_item.rb
class LineItem < ApplicationRecord
    belongs_to :item, class_name: "item", foreign_key: "item_id"
end

app/models/orderable.rb
class Orderable < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  def total
    product.price * quantity 
  end
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :orderables

    has_many :carts, through: :orderables #through: :join_association, source: :join_association_table_foreign_key_to_carts_table
    
    has_rich_text :content
    
    has_one_attached :thumbnail
    has_one_attached :video
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
    @render_cart = false
    @show_cart = Orderable.all
    #debugger
  end

  def add
    if user_signed_in?
      @product = Product.find_by(id: params[:id])
      quantity = params[:quantity].to_i
      current_orderable = @cart.orderables.find_by(product_id: @product.id)
      if current_orderable && quantity > 0
        current_orderable.update(quantity:)
      elsif quantity <= 0 
        current_orderable.destroy
      else
        @cart.orderables.create(product: @product, quantity:)
      end
      
      #Increase the product number tag in the header
      @orderable_count= Orderable.count()
      #if @orderable_count > 0
        respond_to do |format|
          format.turbo_stream do
            render turbo_stream: [turbo_stream.replace('cart',
                                                        partial: 'cart/cart',
                                                        locals: {cart: @cart }),
                                  turbo_stream.replace(@orderable_count)]
          end
        end
    else
      redirect_to new_user_session_path
    end
    
  end

  def remove
    @orderable = Orderable.find_by(id: params[:id])
    if @orderable.destroy
      @orderable_count= Orderable.count()
      respond_to do |format|
        format.html { redirect_to cart_url, notice: "Product was successfully destroyed." }
        # format.turbo_stream do
        #   render turbo_stream: turbo_stream.replace('cart',
        #     partial: 'cart/cart',
        #     locals: {cart: @orderable_count })
        # end
      end
    else
      puts "Nothing happen!"
    end
  end

    #redirect_to cart, notice: "Produit à été supprimé avec succés."
end

app/controllers/cours_controller.rb
class CoursController < ApplicationController
  before_action :set_cour, only: %i[ show edit update destroy ]

  # GET /cours or /cours.json
  def index
    @cours = Cour.all
  end

  # GET /cours/1 or /cours/1.json
  def show
    @line_items =  LineItem.new
  end

  # GET /cours/new
  def new
    @cour = Cour.new
  end

  # GET /cours/1/edit
  def edit
  end

  # POST /cours or /cours.json
  def create
    @cour = Cour.new(cour_params)

    respond_to do |format|
      if @cour.save
        format.html { redirect_to cour_url(@cour), notice: "Cour was successfully created." }
        format.json { render :show, status: :created, location: @cour }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cours/1 or /cours/1.json
  def update
    respond_to do |format|
      if @cour.update(cour_params)
        format.html { redirect_to cour_url(@cour), notice: "Cour was successfully updated." }
        format.json { render :show, status: :ok, location: @cour }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cours/1 or /cours/1.json
  def destroy
    @cour.destroy

    respond_to do |format|
      format.html { redirect_to cours_url, notice: "Cour was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cour
      @cour = Cour.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cour_params
      params.require(:cour).permit(:title, :content, :thumbnail, :video, :description)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :description, :price, :thumbnail, :video, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/cours_helper.rb
module CoursHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/cart/_cart.html.erb
<%#= turbo_frame_tag "cart" do %>
    <%#= @orderable_count %>
    <!--h1>Cart</h1>
    <%# if @cart.orderables.count > 0 %>
        <%#= render 'cart/orderables' %>
        <p>Total: <%#= @cart.total %></p>
    <%# else %>
        <p>Your cart is empty</p-->
    <%# end %>
<%# end %>

<%= turbo_frame_tag "cart" do %><%= @orderable_count %><% end %>

app/views/cart/_orderables.html.erb
<% @cart.orderables.each do |orderable| %>
  <% product = orderable.product %>
    <div id="<%= "cart-#{product.id}" %>">
        <div class="" style="display:flex;justify-content:space-between;margin: 0em 5em;"> 
            <strong>Title:</strong>
            <%= product.title %>
        
            <strong>Description:</strong>
            <%= product.description %>
        
            <strong>Price:</strong>
            <%= product.price %>

            <%= form_with(url: cart_add_path) do |f| %>
                <%= f.hidden_field :id, value: product.id %>
                <%= f.number_field :quantity, value: orderable.quantity, min: 0 %>
                <%= f.submit "Add To Cart" %>
            <% end %>

            <%= form_with(url: cart_remove_path) do |f| %>
                <%= f.hidden_field :id, value: orderable.id %>
                <%= f.submit "X" %>
            <% end %>
        </div>
    </div>
<% end %>

app/views/cart/show.html.erb
<h1 class="d-flex justify-content-center">Mon panier: <span class="border-bottom border-warning border-5"> <%= @cart.total %>€ </span></h1>

<div class="row">
    <% if @cart.nil? %>
        <h1><%= "Votre panier est vide"  %></h1>
    <% end %>
    <% @show_cart.each do |orderable| %>
        <% product = orderable.product %>
    
        <!--p><%#= product.title %> * <%= orderable.quantity %> = $<%= product.price %> * <%= orderable.quantity %></p-->
        <div class="col-md-12">
            <div class="d-flex justify-content-center">
                <div class="card mb-3" style="max-width: 540px;">
                    <div class="row g-0">
                        <div class="col-md-5">
                            <a href="<%= product_path(product) %>">
                                <%= image_tag product.thumbnail, class:"img-fluid rounded-start", style:"height:100%", alt:"..." if product.thumbnail.present? %>
                            </a>
                        </div>
                        <div class="col-md-5">
                            <div class="card-body">
                                <h3 class="card-title"><%= link_to product.title, product, class:"text-dark" %></h3>
                                <h5 class="card-text"><%= orderable.quantity %> X <span class="text-warning">€<%= product.price %></span> </h5>
                                    <%= form_with(url: cart_remove_path) do |f| %>
                                        <%= f.hidden_field :id, value: orderable.id %>
                                        <%= f.submit "Annuler", class:"btn btn-outline-secondary" %>
                                    <% end %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <% end %>

</div>

<% if @card.nil? %>
<% end %>

<div class="container d-flex justify-content-center col-md-4 p-3 bg-info bg-opacity-10 border border-dark border-0 mt-3 mb-4 ">
    <h2 class="card-text ">Total <%= @cart.total %>€</h2>
</div>

app/views/cours/_cour.html.erb
<div id="<%= dom_id cour %>" style="margin-top:10px;">
  <div class="d-flex justify-content-center">
    <h1 class="py-5"><%= cour.title %> €80.00</h1>
  </div>

  <div class="row mx-3">
    <div class="col-md-8 px-5" style="">
      <div class="d-flex justify-content-center">
        <%= video_tag url_for(cour.video), :controls => true, style:"width:100%;height:auto" if cour.video.video?%>
      </div>
      
      <div class="container p-5">
        <div class="d-flex justify-content-center">
          <%= cour.content %>
        </div>
      </div>
    </div>

    <div class="d-flex justify-content-center col-md-2" style="padding-top:19%;">
      <%= form_with model: @line_items, url: add_to_cart_line_item_path  do |form| %>
        <%= form.submit "Ajouter dans mon panier", class:"bi-cart-fill me-1 btn btn-info" %>
      <% end %>
    </div>

    <div>
      <%#= link_to image_tag(cour.thumbnail, style:"width:400px;height:auto"), cours_path if cour.thumbnail.present? %>
    </div-->

    <%#= link_to "Show this cour", cour %>
  </div>
</div>

<!--div class="container py-5">
  <div class="d-flex justify-content-center">
    <div class="col-12">
        <div class="card" style="width: auto; border: 2px solid #FF7733;"> 
		      <%#= image_tag(cour.thumbnail, style:"width:100%;height:25%", class:"card-img-top") if cour.thumbnail.present? %>
          <div class="card-body">
            <h5 class="card-title">Basic Card</h5>
            <p class="card-text">Sed semper eros aliquam nulla vulputate egestas. Suspendisse porttitor velit felis. </p>
            <a href="#" class="btn btn-primary">Go somewhere</a>
            <div class="d-flex justify-content-sm-around flex-nowrap mb-3">
              <span class="btn btn-secondary">
                <%#= link_to "Voir plus...", cour, class:"text-white" %>
              </span>
              <span class="ms-5 pricing-card-title" style="font-size:1.5rem; padding:5px; border: 2px solid #FF7733">
                89€
              </span>
            </div>
            
          </div>
      </div>
    </div>
  </div>
</div-->

app/views/cours/_form.html.erb
<div class="container-fluid" style="">
  <%= form_with(model: cour) do |form| %>
    <% if cour.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(cour.errors.count, "error") %> prohibited this cour from being saved:</h2>

        <ul>
          <% cour.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group col-md-6">
      <%= form.label :title, style: "display: block" %>
      <%= form.text_field :title, class:"form-control" %>
    </div>

    <div class="form-group col-md-6">
      <%= form.label :thumbnail %>
      <%= form.file_field :thumbnail, class:"form-control" %>
    </div>

    <div class="form-group col-md-6">
      <%= form.label :video %>
      <%= form.file_field :video, class:"form-control" %>
    </div>

    <div class="form-group col-md-6">
      <%= form.label :description, style: "display: block" %>
      <%= form.text_area :description, class:"form-control" %>
    </div>

    <div class="form-group col-md-12">
      <%= form.label :content, style: "display: block" %>
      <%= form.rich_text_area :content, class:"form-control" %>
    </div>
<br/>
    <div class="form-group col-md-6">
      <%= form.submit "Enregistrer", class:"btn btn-primary" %>
    </div>
  <% end %>
<br/>

</div>

app/views/cours/edit.html.erb
<h1>Editing cour</h1>

<%= render "form", cour: @cour %>

<br>

<div>
  <%= link_to "Show this cour", @cour %> |
  <%= link_to "Back to cours", cours_path %>
</div>

app/views/cours/index.html.erb
<div class="" style="">
  <p style="color: green"><%= notice %></p>

  <h1>
    <%= link_to "New cour", new_cour_path, class:"btn btn-outline-primary" %>
  </h1>
  <div id="cours">
    <main style="">
      <div class="container marketing" style="margin-top:2%;">
        <% @cours.each do |cour| %>
        <hr class="featurette-divider">
          <div class="row featurette mb-4">
            <div class="col-md-7">
              <h2 class="featurette-heading fw-normal lh-1"><%= cour.title %><span class="text-body-secondary"> Prix: €80.00</span></h2>
              <p class="lead"><%= cour.description %></p>
              <%= link_to "Voir +", cour, class:"btn btn-warning mt-auto m-2", style:"" %> 
              <%= link_to "Panier", "#", class:"btn btn-danger mt-auto m-2", style:"" %> 
            </div>
            <div class="col-md-5">
              <%= image_tag cour.thumbnail, class:"card-img-top", alt:"..." if cour.thumbnail.present? %>
            </div>
          </div>
        <% end %>
        <hr class="featurette-divider">
      </div>
  </div>
</div>

app/views/cours/index_old.erb
<div class="" style="">
  <p style="color: green"><%= notice %></p>

  <h1>
    <%= link_to "New cour", new_cour_path, class:"btn btn-outline-primary" %>
  </h1>
  <div id="cours">
    <main style="">
      <div class="container marketing" style="margin-top:2%;">
        <hr class="featurette-divider">
        <% @cours.each do |cour| %>
          <div class="row featurette">
            <div class="col-md-7">
              <h2 class="featurette-heading fw-normal lh-1"><%= cour.title %><span class="text-body-secondary"> Prix: €80.00.</span></h2>
              <p class="lead"><%= cour.description %></p>
              <%= link_to "Voir +", cour, class:"btn btn-warning mt-auto m-2", style:"" %> 
              <%= link_to "Panier", "#", class:"btn btn-danger mt-auto m-2", style:"" %> 
            </div>
            <div class="col-md-5">
              <%= image_tag cour.thumbnail, class:"card-img-top", alt:"..." if cour.thumbnail.present? %>
              <div class="text-start">
              </div>
            </div>
          </div>
          <hr class="featurette-divider mb-4">
        <% end %>
      </div>

  <!-- Related items section-->
  <%# <section class="py-5 bg-light">
    <div class="container px-4 px-lg-5 mt-5">
      <h2 class="fw-bolder mb-4">Related products</h2>
      <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-3 justify-content-center">
      <% @cours.each do |cour| %>
        <div class="col mb-5">
          <div class="card h-100">
            <!-- Product image-->
            <!--img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." / -->
            <%#= image_tag cour.thumbnail, class:"card-img-top", alt:"..." if cour.thumbnail.present? %>
            <!-- Product details-->
            <div class="card-body p-4">
              <div class="text-center">
                <!-- Product name-->
                <h5 class="fw-bolder">Fancy Product</h5>
                <!-- Product price-->
                $40.00 - $80.00
              </div>
            </div>
            <!-- Product actions-->
            <div class="card-footer py-4 pt-0 border-top-0 bg-transparent">
              <div class="text-center">
                <!--a class="btn btn-outline-dark mt-auto mx-2" href="#">Voir +</a-->
                <%= link_to "Voir +", cour, class:"btn btn-outline-dark mt-auto m-2", style:"" %> 
                <%= link_to "Panier", "#", class:"btn btn-outline-dark mt-auto m-2", style:"" %> 
                <!--a class="btn btn-outline-dark mt-auto" href="#">Panier</a -->
              </div>
            </div>
          </div>
        </div>
      <% end %>
      </div>
      
      
    </div>
  </section> %>

    <!--div class="container d-flex justify-content-center">
    <div class="row justify-content-center">
      <% #@cours.each do |cour| %>
        <div class="card" style="width: 25rem; margin:2%;padding:0%; border: 3px solid #FF7733;border-top-left-radius: 2%;border-top-right-radius: 2%;">
		      <%#= image_tag(cour.thumbnail, style:"width:auto;height:auto;", class:"card-img-top", alt:"...") if cour.thumbnail.present? %>
          <div class="card-body">
            <h5 class="card-title"><%#= cour.title %></h5>
            <p class="card-text"><%#= cour.description %></p>
            <div class="d-flex justify-content-between">
              <%#= link_to "Voir plus...", cour, class:"btn btn-outline-primary", style:"" %> 
              <span class="fw-bold text-decoration-underline" style="border-top: 2px solid #FF7733;font-size:2rem;">89€</span>
            </div>
          </div>
        </div>
          <%#= render cour %>
      <%# end %>
    </div>
    </div-->
  </div>
</div>

app/views/cours/new.html.erb
<div class="container d-flex justify-content-center">
  <div class="row">
    <h1>New cour</h1>

    <%= render "form", cour: @cour %>

    <br>
    <br>

    <div>
      <%= link_to "Annulé",cours_path, class:"btn btn-outline-primary" %>
    </div>
  </div>
</div>
<br/>

app/views/cours/show.html.erb
<div>
  <p style="color: green"><%= notice %></p>
    <div class="d-flex px-5">
      <%= link_to "Retour", cours_path, class:"btn btn-secondary mx-3" %> |
      <%= link_to "Modifer ce cours", edit_cour_path(@cour), class:"btn btn-warning mx-3" %> 
      <%= button_to "Supprimer ce cours", @cour, method: :delete, class:"btn btn-danger " %>
    </div>  
    <%= render @cour %>
    <div class="d-flex px-5 mb-5">
      <%= link_to "Retour", cours_path, class:"btn btn-secondary mx-3" %> | 
      <%= link_to "Modifer ce cours", edit_cour_path(@cour), class:"btn btn-warning mx-3" %>

      <%= button_to "Supprimer ce cours", @cour, method: :delete, class:"btn btn-danger " %>
    </div>  
  <div>
  </div>

</div>

app/views/products/_form.html.erb
<div class="container d-flex justify-content-center" style="width:75%">
    <%= form_with(model: product) do |form| %>
    <% if product.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>
        <ul>
          <% product.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group" >
      <%= form.label :title, style: "display: block" %>
      <%= form.text_field :title, class:"form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :thumbnail %>
      <%= form.file_field :thumbnail, class:"form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :video %>
      <%= form.file_field :video, class:"form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :description, style: "display: block" %>
      <%= form.text_field :description, class:"form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :price, style: "display: block" %>
      <%= form.text_field :price, class:"form-control" %>
    </div>
</div>

<div class="container justify-content-center col-md-10">
  <b><%= form.label :contenu, style: "display: block" %></b>
  <%= form.rich_text_area :content,cols: 30, rows: 10  %>
  <div class="my-4">
    <%= form.submit "Enregistrer", class:"btn btn-warning col-md-4" %>
  </div>
</div>

<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>" style="margin-top:10px;">
  <div class="row d-flex px-3">
    <div class="col-md-8" style="">
      <div class="d-flex justify-content-center">
        <%= video_tag url_for(product.video), :controls => true, style:"width:100%;height:auto" if product.video.video?%>
      </div>
    </div>

    <div class="col-md-4" style="margin-top:-0.6%"> 
  
      <div class="d-flex justify-content-center">
        <h1 class=""><%= product.title %></h1>
      </div>

      <div class="d-flex justify-content-center h2">
        <%= product.price %>€
      </div>

      <div class="d-flex justify-content-center">
        <%= product.description %>
      </div>

      <div class="d-flex justify-content-center mt-4">
        <%= form_with(url: cart_add_path) do |f| %>
          <%= f.hidden_field :id, value: product.id %>
          <%= f.hidden_field :quantity, value:1, min: 1, max: 1 %>
          <%= f.submit "Ajouter au panier", class:"btn btn-outline-primary" %>
        <% end %>
      </div>
    </div>
  </div>
      
  <div class="container p-5">
    <div class="d-flex justify-content-center">
      <%= product.content %>
    </div>
  </div>
</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<main>
  <p style="color: green"><%= notice %></p>

  <h1><%= link_to "Ajouter un produit", new_product_path, class:"link-orange link-offset-2 link-underline-opacity-100-hover mx-4" %></h1>
<br>
    <div class="container marketing">
      <% @products.each do |product| %>
        <div class="row featurette" style="margin-bottom:4%;">
            <div class="col-md-7 order-md-2" style="border-bottom:4px solid orange; margin-top:-7px;">
              <h2 class="featurette-heading"><%= product.title %><span class="text-muted"> <%= product.price %>€</span></h2>
              <p class="lead"><%= product.description %>.</p>
              <div class="d-flex">
              <%= link_to "Voir +", product, class:"btn btn-outline-dark mt-auto m-2", style:"" %> 
              <%= form_with(url: cart_add_path) do |f| %>
                <%= f.hidden_field :id, value: product.id %>
                <%= f.hidden_field :quantity, value:1, min: 1, max: 1 %>
                <%= f.submit "Ajouter au panier", class:"btn btn-outline-dark mt-auto m-2" %>
              <% end %>
              </div>
            </div>
          <div class="col-md-5 order-md-1" style="margin-left:0%";>
              <%= image_tag product.thumbnail, class:"card-img-top featurette-image img-fluid mx-auto", alt:"..." if product.thumbnail.present? %>
          </div>

          <div class="bg-light">

          </div>
          
      <% end %>
    </div>
</main>

app/views/products/new.html.erb
<h1 class="d-flex justify-content-center">Ajouter un cours</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>
<div class="d-flex m-4 justify-content-center">
  <%= link_to "Retour", products_path, class:"btn btn-outline-info mx-2" %>
  <%= link_to "Modifier", edit_product_path(@product), class:"btn btn-outline-warning mx-2" %>

  <%= button_to "Supprimer", @product, method: :delete, class:"btn btn-outline-danger mx-2" %>
</div>

<%= render @product %>

<div class="d-flex m-4 justify-content-center">
  <%= link_to "Retour", products_path, class:"btn btn-outline-info mx-2" %>
  <%= link_to "Modifier", edit_product_path(@product), class:"btn btn-outline-warning mx-2" %> 

  <%= button_to "Supprimer", @product, method: :delete, class:"btn btn-outline-danger mx-2" %>
</div>