config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'cart', to: 'cart#show'
  post 'cart/add'
  post 'cart/remove'
  resources :products
  resources :cards
  resources :items
  resources :line_items do
    member do
      post :add_to_cart
    end
  end
  resources :cours
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/card.rb
class Card < ApplicationRecord
    has_many :items
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :orderables

    has_many :products , through: :orderables #through: :join_association, source: :join_association_table_foreign_key_to_carts_table

    def total
      orderables.to_a.sum { |orderable| orderable.total}
    end
end

app/models/cour.rb
class Cour < ApplicationRecord
    #belongs_to :object, class_name: "object", foreign_key: "object_id"
    has_rich_text :content
    
    has_one_attached :thumbnail
    has_one_attached :video
end

app/models/item.rb
class Item < ApplicationRecord
    has_many :line_items

    belongs_to :card, class_name: "card", foreign_key: "card_id"
end

app/models/line_item.rb
class LineItem < ApplicationRecord
    belongs_to :item, class_name: "item", foreign_key: "item_id"
end

app/models/orderable.rb
class Orderable < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  def total
    product.price * quantity 
  end
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :orderables

    has_many :carts, through: :orderables #through: :join_association, source: :join_association_table_foreign_key_to_carts_table
    
    has_rich_text :content
    
    has_one_attached :thumbnail
    has_one_attached :video
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
    @render_cart = false
    @show_cart = Orderable.all
    #debugger
  end

  def add
    if user_signed_in?
      @product = Product.find_by(id: params[:id])
      quantity = params[:quantity].to_i
      current_orderable = @cart.orderables.find_by(product_id: @product.id)
      if current_orderable && quantity > 0
        current_orderable.update(quantity:)
      elsif quantity <= 0 
        current_orderable.destroy
      else
        @cart.orderables.create(product: @product, quantity:)
      end
      
      #Increase the product number tag in the header
      @orderable_count= Orderable.count()
      #if @orderable_count > 0
        respond_to do |format|
          format.turbo_stream do
            render turbo_stream: [turbo_stream.replace('cart',
                                                        partial: 'cart/cart',
                                                        locals: {cart: @cart }),
                                  turbo_stream.replace(@orderable_count)]
          end
        end
    else
      redirect_to new_user_session_path
    end
    
  end

  def remove
    @orderable = Orderable.find_by(id: params[:id])
    if @orderable.destroy
      @orderable_count= Orderable.count()
      respond_to do |format|
        format.html { redirect_to cart_url, notice: "Product was successfully destroyed." }
        # format.turbo_stream do
        #   render turbo_stream: turbo_stream.replace('cart',
        #     partial: 'cart/cart',
        #     locals: {cart: @orderable_count })
        # end
      end
    else
      puts "Nothing happen!"
    end
  end

    #redirect_to cart, notice: "Produit à été supprimé avec succés."
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/cours_helper.rb
module CoursHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Awformation</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/header" %>
    
    <%#= render "cart/cart" if @render_cart %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/shared/_footer.html.erb
<!-- Footer-->
<div class="px-5 bg-dark" style="border-bottom: 5px solid orange;">
  <footer class="py-5">
    <div class="row text-white">
      <div class="col-5 col-md-2 mb-3">
        <h5>Section</h5>
        <ul class="nav flex-column">
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">Accueil</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">Secteurs</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">Prix</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">FAQs</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">A propos</a></li>
        </ul>
      </div>

      <div class="col-6 col-md-2 mb-3">
        <h5>Domaine d'activité</h5>
        <ul class="nav flex-column">
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">Cours informatique en ligne</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">Developpement d'application</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">Infographie</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white">Cours d'Arabe</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white"></a></li>
        </ul>
      </div>

      <div class="col-md-5 offset-md-1 mb-3">
          <h5>Contactez-nous par: </h5>
          <p></p>
          <div class="d-flex flex-column flex-sm-row w-100 gap-2">
            <i class="fa-brands fa-font-awesome"></i>
            <i class="fa-solid fa-user-secret"></i>
            <i class="fa-regular fa-bell"></i>
            <i class="fa-solid fa-user-secret"></i>
          </div>
      </div>
    </div>
</footer>

app/views/shared/_header.html.erb
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-light bg-dark" style="border-top:10px solid orange;">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand text-white" href="#!">Start Bootstrap</a>
        <button class="navbar-toggler text-white" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                <li class="nav-item"><a class="nav-link active text-white" aria-current="page" href="<%= root_path %>">Acceuil</a></li>
                <li class="nav-item"><a class="nav-link text-white" href="<%= products_path %>">Formation</a></li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-white" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Nos Produits</a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item text-dark" href="#!">Informatique</a></li>
                        <li><hr class="dropdown-divider" /></li>
                        <li><a class="dropdown-item text-dark" href="#!">Developpement</a></li>
                        <li><a class="dropdown-item text-dark" href="#!">Infographie</a></li>
                        <li><a class="dropdown-item text-dark" href="#!">Administration Systémes & Réseaux</a></li>
                    </ul>
                </li>
                <% if !user_signed_in? %>
                    <li class="nav-item">
                        <%= link_to "Se Connecter", new_user_session_path, class:"nav-link text-white" %>
                    <li class="nav-item">
                        <%= link_to "S'inscrire", new_user_registration_path, class:"nav-link text-white" %>
                    </li>
                <% else %>
                    <li class="nav-item">
                        <%= link_to "Se déconnecter", destroy_user_session_path, class:"nav-link text-white", method: :delete, data: { turbo_method: :delete } %>
                    </li>
                <% end %>
            </ul>

            <form class="d-flex">
                <a href=" <%= cart_path %> " class="link-offset-2 link-underline text-white">
                    <button class="btn btn-outline-light" type="submit">
                        <i class="bi-cart-fill me-1 text-white"></i>
                        Cart
                        <span class="badge bg-white text-black ms-1 rounded-pill"><%= turbo_frame_tag "cart" do %><%= @orderable_count %><% end %></span>
                    </button>
                    </a>
            </form>
        </div>
    </div>
</nav>